export const FieldLabelsConstant = {
   LABELS: {
      ACTION: "Action",
      ACTION_COMPLETED_DATE: "Action Completed Date",
      ACTION_DESCRIPTION: "Action Description",
      ACTION_PLAN: "Action Plan",
      ACTION_REQUIRED: "Action Required",
      ACTION_STATUS: "Action Status",
      ACTION_TARGET_DATE: "Action Target Date",
      ACTIONS: "Actions",
      ACTIVE: "Active",
      ACTIVE_IN_ACTIVE: "Active In-active",
      ACTIVITY: "Activity",
      ACTIVITY_FLAG: "Activity Flag",
      ACTIVITY_ID: "Activity Id",
      ACTIVITY_NAME: "Activity Name",
      ACTIVITY_POSITION: "Activity Position",
      ACTIVITY_POSITION_ID: "Activity Position Id",
      ACTIVITY_POSITION_SEQ: "Activity Position Seq",
      ACTIVITY_TYPE: "Activity Type",
      ACTUAL_FAULT_DISTANCE: "Act Fault",
      ADEE_SECTION: "Adee Section",
      ALLOCATION: "Allocation",
      AGENCY:"Agency",
      ALREADY_DONE: "Already Done",
      ALTITUDE: "Altitude",
      AMOUNT: "Amount",
      AMBIENT_TEMP:"Ambient Temp",
      TEMP_DIFF: "Temp Diff",
      FIXED_DIFF: "Fixed Diff",
      CCLAMP_DIFF: "C Clamp Diff",
      TOWERCAR_TYPE:"TW Type",
      TOWERCAR_NO:"TW Id",
      POH:"Next POH",
      AOH:"Next AOH",
      STATUS_DATE:"Status Date",
      NEW_STATUS:"New status",
      CURRENT_STATUS:"Current Status",
      CHANGE_OF_STATUS:"New status",
      CRITICALITY: "Criticality",
      MANF_YEAR:"Mnf Year",
      APPROVAL_DATE: "Approval Date",
      APPROVED_BY: "Approved By",
      APPROVED_DATE: "Approved Date",
      ASA_SEQ_ID: "Asa Seq Id",
      ASSET_DESCRIPTION: "Asset Description",
      ASSET_ID: "Asset Id",
      ASSET_SCHEDULE: "Asset Schedule",
      ASSET_TYPE: "Asset Type",
      ASSET_TYPE_RLY_ID: "Asset Type Rly Id",
      ASSET_TYPE_SCHEDULE_NAME: "Asset Type Schedule Name",
      AUTHORISATION_DATE: "Authorisation Date",
      AUTHORITY: "Authority",
      ASSISTANCE:"Assistance",
      TYPE_OF_ASSISTANCE:"Type Of Assistance",
      BETWEEN_TRAINS: "Between Trains",
      BRAND_NAME: "Brand Name",
      CASCADE_ASSETS: "Cascade Assets",
      CATEGORY_NAME: "Category Name",
      CAUSE_OF_FAILURE: "Cause Of Failure",
      CHAINAGE: "Chainage",
      CHAINAGE_REMARK: "Chainage Remark",
      CHARGING_DATE: "Charging Date",
      CHECK_LIST: "Check List",
      CLOSE_TIME: "Close Time",
      CLOSED_REMARKS: "Closed Remarks",
      REMARKS_SHUNTING:"Remarks Shunting",
      REMARKS_NO:"Remarks No",
      AUTO_DEAD:"Auto Dead",
      C_CLAMP: "C-Clamp",
      CMD: "CMD",
      COMMENTS: "Comments",
      CODE:"Code",
      COMPLETION_DATE: "Completion Date",
      COMPLIANCE: "Compliance",
      COMPLIANCE_BY: "Compliance By",
      COMPLIED_BY: "Compiled By",
      COMPLIED_DATE: "Compiled Date",
      CONDITION: "Condition",
      COMMENCEMENT_DATE:"Project Actual Date",
      CREATED_ON: "Created On",
      CRITERIA: "Criteria",
      CROSS_OVER: "Cross Over",
      CRS_AUTHORISATION: "CRS Authorisation",
      CRS_INSPECTION: "CRS Inspection",
      CURRENT: "Current",
      CURVATURE: "Curvature",
      CURVATURE_REMARK: "Curvature Remark",
      COUNT:"Count",
      DATE: "Date",
      DATE_OF_COMMISSION: "Date Of Commission",
      DATE_OF_COMPLETION: "Date Of Completion",
      DATE_OF_COMPLIED: "Date Of Complied",
      DATE_OF_INSPECTION: "Date Of Inspection",
      DATE_OF_MANUFACTURE: "Date Of Manufacture",
      DATE_OF_RECEIVED: "Date Of Received",
      DATE_OF_STIPULATION: "Date Of Stipulation",
      DAY_PROGRESS: "Day Progress",
      MONTHLY_PROGRESS: "Monthly Progress",
      CUM_PROGRESS: "Cum Progress",
      MONTHLY_TARGET: "Monthly Target",
      CUM_TARGET: "Cum Target",
      DEPO: "Depo",
      DEPO_TYPE: "Depo Type",
      DEPOT: "Depot",
      DEPOT_NAME: "Depot Name",
      DEPOT_TYPE: "Depot Type",
      DESCRIPTION: "Description",
      DETAILS: "Details",
      DETAILS_OF_ISSUE: "Details Of Issue",
      DETAILS_OF_MAINT: "Details Of Maint",
      DISPLAY_ORDER: "Display Order",
      DIVISION: "Division",
      DIVISION_LOCAL: "Div/Local",
      LOCAL:"Local  ",
      DN_SECTION: "Dn Section",
      DN_SECTION_NAME: "Dn Section Name",
      STATION_TYPE:"Station Type",
      DOCUMENTS: "Documents",
      DONE_BY: "Done By",
      DOUBLING_TRIPPLING: "Doubling Tripling",
      DOWN_SECTION: "Down Section",
      DOWN_SECTION_NAME: "Down Section Name",
      DRIVE: "Drive",
      DURATION: "Duration",
      DIVAGGREGATION:"Div Agg",
      SUBDIVAGGREGATION:"SUB DIV AGG",
      DEPOTAGGREGATION:"DEPO AGG",
      DATE_OF_WORK:"Date Of Work",
      ELE_SECTION: "Ele Section",
      ELECTRIFIED_RKM: "Electrified RKM",
      ELECTRIFIED_TKM: "Electrified TKM",
      ELEMENTARY_SECTIONS: "Elementary Sections",
      ENERGISED_DATE: "Energised Date",
      ENG_FEATURE: "Eng Feature",
      EQUIPMENT: "Equipment",
      END_KM:"End KM",
      EQUIPPED_DATE: "Equipped Date",
      ESTIMATED_REVISED_ANTICIPATED_COST: "Estimated Revised Anticipated Cost",
      EXECUTED_BY: "Executed By",
      EXECUTION_AGENCY: "Execution Agency",
      EXPIRY_DATE: "Expiry Date",
      EXTENDED_DURATION: "Extended Duration",
      EXPECTED_COMPLETION:"Expected Completion",
      EXTENDED_FROM: "Extended From",
      EXTENDED_FROM_DATE: "Extended From Date",
      EXTENDED_OFF: "Extended Off",
      EXTENDED_TO_DATE: "Extended To Date",
      FACILITY_NAME: "Facility Name",
      FACILITY_TYPE_ID: "Facility Type Id",
      FAILURE_ACTIONS: "Failure Actions",
      FAILURE_FROM: "Failure From",
      FAILURE_FROM_DATE: "Failure From Date",
      FAILURE_SECTION: "Failure Section",
      FAILURE_THRU: "Failure Thru",
      FAILURE_TO_DATE: "Failure To Date",
      FAULT_DISTANCE: "Fault Dist",
      FEED_EXTENDED_DURATION: "Feed Extended Duration",
      FEED_EXTENDED_FROM: "Feed Extended From",
      FEED_EXTENDED_FROM_DATE_TIME: "Feed Extended From Date Time",
      FEED_EXTENDED_THRU: "Feed Extended Thru",
      FEED_EXTENDED_THRU_DATE_TIME: "Feed Extended Thru Date Time",
      FEED_OF: "Feed Of",
      FEED_OFF: "Feed Off",
      FEEDER: "Feeder",
      FINANCIAL_PROGRESS_PERCENTAGE: "Financial Progress Percentage",
      FIXED: "Fixed",
      FOOT_INSPECTION: "Foot Inspection",
      FOOT_PATROLLING: "Foot Patrolling",
      FOOT_PLATE_INSPECTION: "Foot Plate Inspection",
      FP_SECTION: "FP Section",
      FREQUENCY: "Frequency",
      FROM_DATE: "From Date",
      FROM_DATE_TIME: "From",
      FROM_KILOMETER: "From KM",
      FROM_SEQ:"From Seq",
      FROM_LOCATION: "From Location",
      FROM_LOCATION_TYPE:"From Location Type",
      FROM_TIME: "From Time",
      DATE_OF_CHANGE:"Date Of Change",
      FUNCTIONAL_TYPE: "Functional Type",
      FUNCTIONAL_UNIT: "Functional Unit",
      FUNCTIONAL_UNIT_ID: "Functional Unit Id",
      FUNCTIONAL_UNIT_NAME: "Functional Unit Name",
      FUNCTIONAL_UNIT_TYPE: "Functional Unit Type",
      FUNCTIONAL_UNIT_TYPE_ID: "Functional Unit Type Id",
      FOUNDATION:"FOundation",
      GANTRY_CODE: "Gantry Code",
      SECTOR_CODE:"Sector Code",
      SUB_SECTOR_CODE:"Sub Sector Code",
      ELEMENTARY_SECIONS_CODE:"Elementary Sections Code",
      GEN_OPS: "Gen Ops",
      GUAGE: "Guage",
      GROUP:"Group",
      AVOIDABLE:"Avoidable",
      REAMRK_BRIEF:"Remark Brief",
      REMARK_DETAILS:"Reamrk Details",
      HEADING: "Heading", 
      DRIVE_ID:"Drive No",
      IDS: "Ids",
      IMPACT: "No of Trains Effected",
      INCHARGE: "Incharge",
      INDICATION: "Indication",
      INSPECTION: "Inspection",
      INSPECTION_BY: "Inspection By",
      INSPECTION_ID: "Inspection Id",
      INSPECTION_TYPE: "Inspection Type",
      INTERNAL_EXTERNAL: "Int/ Ext",
      IS_DPR: "Is DPR",
      IS_ID_REQUIRED: "Is Id Required",
      IS_OBJECT_ID_REQUIRED:"Is Object Id Require",
      IS_CHECKLIST:"Is CheckList",
      IS_NORMALLY_OPENED: "IS Normally Opened",
      JMR: "JMR",
      KILOMETER: "KM",
      KVAH_CONSUMPTION: "KVAH Consumption",
      KVAH_CURRENT: "KVAH Current",
      KVAH_OLD: "KVAH Old",
      KWH_CONSUMPTION: "KWH Consumption",
      KWH_CURRENT: "KWH Current",
      KWH_OLD: "KWH Old",
      LATEST_REVISED_COST: "Latest Revised Cost",
      LATITUDE: "Latitude",
      LETTER_NO: "Letter No",
      LOCATION: "Location",
      LOA_NO:"Loa No",
       LOA_DATE:"Loa Date",
       LINE_TYPE:"Line Type",
      LOCATION_POSITION: "Location Position",
      LOAD_RELIEF_BREAK_DOWN:"Load Relief/Break Down",
      LOCATION_TYPE: "Location Type",
      LONGITUDE: "Longitude",
      LONGITUDINAL_DN: "Longitudinal Dn",
      LONGITUDINAL_UP: "Longitudinal Up",
      LOWER_LIMIT: "Lower Limit",
      LUG_DATE: "Lug Date",
      MAJOR_SECTION: "Major Section",
      MAJOR_SECTION_ROUTE: "Major Section Route",
      MAKE: "Make",
      MAKE_CODE: "Make Code",
      MAKE_TYPE: "Make Type",
      MATERIAL_CLASSIFICATION: "Material Classification",
      MAX_DEMAND: "Max Demand Of Extended TSS",
      MEASURE_ACTIVITY_LIST: "Measure Activity List",
      MEASURE_ENTRY: "Measure Entry",
      MEASURE_LOWER_LIMIT: "Measure Lower Limit",
      MEASURE_UPPER_LIMIT: "Measure Upper Limit",
      METER_MAKE: "Meter Make",
      METER_MODEL: "Meter Model",
      METER_NUMBER: "Meter Number",
      MF: "MF",
      MODEL: "Model",
      MODEL_CODE: "Model Code",
      MODEL_TYPE: "Model Type",
      MONTH: "Month",
      MULTIPLICATION_FACTOR: "Multiplication Factor",
      MANUAL_ENTRY:"Manual Entry",
      MINOR_SECTION:"Minor Section",
      NAME: "Name",
      NAME_OF_STAFF: "Name Of Staff",
      NATURE_OF_CLOSURE: "Nat.Clos",
      INTERNAL:"Internal",
      EXTERNAL:"External",
      NON_POWER_BLOCK: "Non Power Block",
      NORMALLY_OPEN: "Normally Open",
      NPB_PROGRESS: "NPB Progress",
      OBSERVATION_CATEGORY: "Observation Category",
      OCCURENCE: "Occurrence",
      OCCURRED_DATE: "Occurred Date",
      OHE_FEATURE: "OHE Feature",
      OHE_MAST: "OHE Mast",
      OHE_MAST_TYPE: "OHE Mast Type",
      OHE_SEQUENCE: "OHE Sequence",
      SPECIAL_WORKS:"Special Works",
      PARENT_FUN: "Parent Fun",
      PARENT_FUN_UNIT: "Parent Fun Unit",
      PB_SECTION: "PB Section",
      PERFORMED_COUNT: "Performed Count",
      PERFORMED_DATE: "Performed Date",
      PHASE: "Phase",
      PHASE_ACTIVITY: "Phase Activity",
      PHASE_ANGLE: "Phase Angle",
      PHYSICAL_PROGRESS_PERCENTAGE: "Physical Progress Percentage",
      PL_NO: "Pl No",
      PLACE: "Place",
      POPULATION: "Population",
      POWER_BLOCK: "Power Block",
      PRIMARY_PARENT_CATEGORY_ID: "Primary Parent Category Id",
      PRIMARY_PRODUCT: "Primary Product",
      PRIMARY_PRODUCT_CATEGORY_ID: "Primary Product Category Id",
      PRIMARY_PRODUCT_CATEGORYID: "Primary Product Category Id",
      PRIORITY: "Priority",
      PRIVATE_RAILWAY: "Private Railway",
      PRODUCT_CATEGORY_ID: "Product Category Id",
      PRODUCT_CATEGORY_TYPE_ID: "Product Category Type Id",
      PRODUCT_ID: "Product Id",
      PRODUCT_TYPE_ID: "Product Type Id",
      PROPOSAL_SCHEME: "Proposal Scheme",
      PROPOSED_DATE: "Proposed Date",
      PROTECTION_LONGITUDINAL_DN: "Protection Longitudinal Dn",
      PROTECTION_LONGITUDINAL_UP: "Protection Longitudinal Up",
      PROTECTION_TRAVERSE_CROSSOVER: "Protection Traverse Crossover",
      PROTECTION_TRAVERSE_TURNOUT: "Protection Traverse Turnout",
      PSI_PROGRESS: "PSI Progress",
      PURPOSE: "Purpose",
      PROJECT:"Project Name",
      PWI: "PWI",
      QUANTITY: "Quantity",
      QUANTITY_UOM_ID: "Quantity Uom Id",
      R_VALUE: "R Value",
      RATE: "Rate",
      READING_DATE: "Reading Date",
      RECTIFIED_DATE: "Rectified Date",
      REFERENCE: "Reference",
      RELAY_IND: "Relay Ind",
      RELAY_INDICATION: "Relay Ind",
      REMARK: "Remark",
      REMARK_ONE: "Remark One",
      REMARK_TWO: "Remark Two",
      REMARKS: "Remarks",
      CASCADE_REMARKS:"Cascade Reamrks",     
      REQUESTED_DATE:"Requested Date",
      RESPONSE_DATE:"ResponseDate",
      RESPONSE_BY:"Response By",
      REPERCUSSION: "Repercussion",
      REPORT_CONTINUE: "Report Continue",
      REPORT_DESCRIPTION: "Report Description",
      REPORTED: "Reported",
      REQUEST_BY: "Request By",
      REQUEST_TO:"Request To",
      REQUEST_DEPARTMENT: "Request Department",
      REQUEST_PERIOD_IN_MIN: "Request Period In MIN",
      RESOLVE_TIME: "Resolve Time",
      RESPONSE: "Response",
      RKM: "RKM",
      RKVAH_LAG_CONSUMPTION: "RKVAH Lag Consumption",
      RKVAH_LAG_CURRENT: "RKVAH Lag Current",
      RKVAH_LAG_OLD: "RKVAH Lag Old",
      RKVAH_LEAD_CONSUMPTION: "RKVAH Lead Consumption",
      RKVAH_LEAD_CURRENT: "RKVAH Lead Current",
      RKVAH_LEAD_OLD: "RKVAH Lead Old",
      RLY_ID: "Rly Id",
      ROOT_CAUSE: "Root Cause",
      S_NO: "S No",
      SANCTION_BY_BOARD: "Sanction By Board",
      SANCTION_COST: "Sanction Cost",
      SATELLITES: "Satellites",
      STANDARD_PHASE_NAME: "Standard Phase Name",
      STANDARD_PHASE_ACTIVITY_NAME: "Standard Phase Activity Name",
      SCHEDULE: "Schedule",
      SCHEDULE_CODE: "Schedule Code",
      SCHEDULE_DATE: "Schedule date",
      SCHEDULE_DURATION: "Schedule Duration",
      SCHEDULE_NAME: "Schedule Name",
      SECTION: "Section",
      SECTION_CODE:"Section Code",
      SECTION_ELECTRIFIED_STATUS: "Section Electrified Status",
      SECTION_END_LOCATION: "Section End Location",
      SECTION_START_LOCATION: "Section Start Location",
      SECTION_STATUS: "Section Status",
      SELECT_EXECUTION_AGENCY: "Select Execution Agency",
      SEQUENCE_CODE: "Sequence Code",
      SEVERITY: "Severity",
      SHORT_DESCRIPTION: "Short Description",
      SIDING_CODE: "Siding Code",
      TRACK_CODE:"Track Code",
      SIDING: "Siding ",
      SIDING_ELECTRIFIED_STATUS: "Siding Electrified Status",
      SIDING_PROPOSED: "Siding Proposed",
      SIDING_STATUS: "Siding Status",
      SIZE: "Size",
      SIDING_YARD_STATION:"Siding/Yard/Station",
      SPECIFICATION: "Specification",
      SPEED: "Speed",
      STAFF_STRENGTH: "Staff Strength",
      START_DATE: "Start Date",
      START_KVAH: "Start KVAH",
      START_KWH: "Start KWH",
      START_RKVAH_LAG: "Start RKVAH Lag",
      START_RKVAH_LEAD: "Start RKVAH Lead",
      START_KM:"Start KM",
      START_TIME: "Start Time",
      STATE: "State",
      SUB_DIVISION:"Sub Division",
      STATE_ELECTRICITY_BOARD: "state Electricity Board",
      STATION: "Station",
      STATION_CODE: "Station Code",
      STATUS: "Status",
      STATUS_REMARKS: "Status Remarks",
      STIPULATION: "Stipulation",
      STOP_TIME: "Stop Time",
      STRIP_DATE: "Strip Date",
      STRUCTURE_TYPE: "Structure Type",
      SUB_ASSET_ID: "Sub Asset Id",
      SUB_ASSET_TYPE: "Sub Asset Type",
      SUB_DIV: "Sub Div",
      SUB_STATION: "Sub Station",
      SUPERVISOR: "Supervisor",
      SUPPLIER: "Supplier",
      SWITCH: "Switch",
      SWITCH_ID: "Switch Id",
      SWITCH_TYPE: "Switch Type",
      SWITCHING_STATION: "Switching Station",
      TARGET: "Target",
      TARGET_DATE: "Target Date",
      TARGET_COMPLETION_DATE:"Target Completion Date",
      TARGET_PLAN: "Target Plan",
      TARGET_PLAN_MONTHS: "Target Plan Months",
      TARGET_QUANTITY: "Target Quantity",
      TARGET_SET_BY: "Target Set By",
      THRU_DATE: "Thru Date",
      THRU_DATE_TIME: "Thru",
      TENDER_VALUE:"Tender Value",
      THRU_TIME: "Thru Time",
      TKM: "TKM",
      TO_DATE: "To Date",
      PROTECTION_CROSSOVER:"Protection Crossover",
      PROTECTION_TURNOUT:"Protection TurnOut",
      TO_KILOMETER: "To KM",
      TO_SEQ:"To Seq",
      TO_LOCATION: "To Location",
      TO_LOCATION_TYPE: "To Location Type",
      TO_PAYMENT: "To Payment",
      TOMORROW_FORECAST: "Tomorrow Forecast",
      TPC_BOARD: "TPC Board",
      TRACK_LINE: "Track Line",
      LINE1:"line1",
      LINE2:"line2",
      TRAIN_NO: "Train No",
      TRAVERSE_TURNOUT: "Traverse Turnout",
      TRIP_IDENTIFIED_FAULT: "Trip Fault",
      TRIP_TIME: "Trip Time",
      TRIP_IDENTIFIED: "Reason Indentified",
      TRIPPED_IDENTIFIED_FAULT: "Tripped Identified Fault",
      TYPE: "Type",
      TYPE_OF_FAILURE: "Type Of Failure",
      TYPE_OF_WORK:"Type Of Work",
      UNIT_NAME: "Unit Name",
      UNIT_OF_MEASURE: "Unit Of Measure",
      UNIT_TYPE: "Unit Type",
      UNITS: "Units",
      UOM: "UOM",
      UOM_OF_DURATION: "Uom Of Duration",
      UP_SECTION: "UP Section",
      UP_SECTION_NAME: "UP Section Name",
      UPPER_LIMIT: "Upper Limit",
      VALID_TILL_DATE: "Valid Till Date",
      VALIDITY: "Validity",
      VOLTAGE: "Volt",
      WARRANTY_AMC_ENDDATE: "Warranty AMC End Date",
      WORK: "Project Name",
      WORK_GROUP: "Group",
      WORK_GROUP_NAME:"Work Group Name",
      WORK_NAME: "Work Name",
      WORK_ORDER_DATE: "Work Order Date",
      WORK_PHASE: "Work Phase",
      WORK_PROGRESS_PERCENTAGE: "work progress percentage",
      WORK_PROGRESS_REMARK: "Work Progress Remark",
      WORK_PHASE_DETAILS:"Work Phase Details",
      X_VALUE: "X Value",
      YEAR: "Year",
      YEAR_OF_SANCTION: "Year Of Sanction",
      Z_CONSTANT: "Z Const",
      ZONE: "Zone",
      DRIVE_CATEGORY:"Drive Category",
      OLD_DRIVE_NAME:"Old Drive Name",
      NEW_DRIVE_NAME:"New Drive Name",
      CHECK:"Check",
      PHASE_NAME:"Phase Name",
      PHASE_ACTIVITY_NAME:"Phase Activity Name",
      DEPENDENCY_TO_START:"Dependency",
      SEQUENCE:"Sequence",
      WEIGHTAGE:"Weightage",
      PLANNED_DATE:"Planned Start Date",
      BATCH:"Batch",
      BRACKET1_INSULATOR_BATCH:"Bracket1 Insulator Batch",
      BRACKET1_INSULATOR_MAKE:"Bracket1 Insulator Make",
      BRACKET2_INSULATOR_BATCH:"Bracket2 Insulator Batch",
      BRACKET2_INSULATOR_MAKE:"Bracket2 Insulator Make",
      BRACKET3_INSULATOR_BATCH:"Bracket3 Insulator Batch",
      BRACKET3_INSULATOR_MAKE:"Bracket3 Insulator Make",
      CAPACITY_RATING:"Capacity Rating",
      CODEL_LIFE:"Codel Life",
      CORE1_INSULATOR_BATCH:"Core1 Insulator Batch",
      CORE1_INSULATOR_MAKE:"Core1 Insulator Make",
      CORE2_INSULATOR_BATCH:"Core2 Insulator Batch",
      CORE2_INSULATOR_MAKE:"Core2 Insulator Make",
      CORE3_INSULATOR_BATCH:"Core3 Insulator Batch",
      CORE3_INSULATOR_MAKE:"Core3 Insulator Make",
      ELEMENTARY_SECTION:"Elementary Section",
      END1_SIDE1:"End1 Side1",
      END2_SIDE2:"End2 Side2",
      IMPLANTATION:"Implantation",
      LINE:"Line",
      NAME_PLATE_DETAILS:"Name Plate Details",
      OEM_SERIAL:"Oem Serial",
      PARENT_ASSET_TYPE:"Parent Asset Type",
      PARENT_ASSET_TYPE_ID:"Parent Asset Type Id",
      PART1:"Part1",
      PART2:"Part2",
      PART3:"Part3",
      PEDESTALL1_INSULATOR_BATCH:"Pedestall1 Insulator Batch",
      PEDESTALL1_INSULATOR_MAKE:"Pedestall1 Insulator Make",
      PEDESTALL2_INSULATOR_BATCH:"Pedestall2 Insulator Batch",
      PEDESTALL2_INSULATOR_MAKE:"Pedestall2 Insulator Make",
      PEDESTALL3_INSULATOR_BATCH:"Pedestall3 Insulator Batch",
      PEDESTALL3_INSULATOR_MAKE:"Pedestall3 Insulator Make",
      POSITION_ID:"Position Id",
      REMARK1:"Remark1",
      REMARK2:"Remark2",
      RLY_ASSIGNED_SERIAL:"Rly Assigned Serial",
      ROD1_INSULATOR_BATCH:"Rod1 Insulator Batch",
      ROD1_INSULATOR_MAKE:"Rod1 Insulator Make",     
      ROD2_INSULATOR_BATCH:"Rod2 Insulator Batch",
      ROD2_INSULATOR_MAKE:"Rod2 Insulator Make",
      ROD3_INSULATOR_BATCH:"Rod3 Insulator Batch",
      ROD3_INSULATOR_MAKE:"Rod3 Insulator Make",
      SOURCE:"Souce",
      STANDARD_PHASE_ID:"Standard Phase Id",
      STAG1_TON9_INSULATOR_BATCH:"Stag1 Ton9 Insulator Batch",
      STAG2_TON9_INSULATOR_BATCH:"Stag2 Ton9 Insulator Batch",
      STAG2_TON9_INSULATOR_MAKE:"Stag2 Ton9 Insulator Make",
      STAG3_TON9_INSULATOR_BATCH:"Stag3 Ton9 Insulator Batch",
      STAG3_TON9_INSULATOR_MAKE:"Stag3 Ton9 Insulator Make",
      STAGGER:"Stagger",
      STAGGER1:"Stagger1",
      STAGGER2:"Stagger2",
      STAGGER3:"Stagger3",
      STAY1_INSULATOR_BATCH:"Stay1 Insulator Batch",
      STAY1_INSULATOR_MAKE:"Stay1 Insulator Make",
      STAY2_INSULATOR_BATCH:"Stay2 Insulator Batch",
      STAY2_INSULATOR_MAKE:"Stay2 Insulator Make",
      STAY3_INSULATOR_BATCH:"Stay3 Insulator Batch",
      STAY3_INSULATOR_MAKE:"Stay3 Insulator Make",
      STRUCTURE:"Structure",
      VENDOR:"Vendor",
      WARRANTY_AMC:"Warranty Amc",
      DOC_CATEGORY:"Doc Category",
      DATE_OF_PAYMENT:"Date Of Payment",
      SORT:"Sort",
      OBSERVATIONS:"Observations",
      CURRENT_KWH:"Current KWH",
      CONSUMPTION_KWH:"Consumption KWH",
      CURRENT_KVAH:"Current KVAH",
      CONSUMPTION_KVAH:"Consumption KVAH",
      OKD_RKVAH_LAG:"Old RKVAH Lag",
      CURRENT_RKVAH_LAG:"Current RKVAH Lag",
      CONSUMPTION_RKVAH_LAG:"Consumption RKVAH Lag",
      OLD_RKVAH_LEAD:"Old RKVAH Lead",
      CURRENT_RKVAH_LEAD:"Current RKVAH Lead",
      CONSUMPTION_RKVAH_LEAD:"Consumption RKVAH Lead",
      OLD_KWH:"Old KWH",
      PF:"PF",
      CPF:"CPF",
      RMD:"RMD",
      VOL_MAX:"Vol Max",
      VOL_MIN:"Vol Min",
      MAX_LOAD:"Max Load",
      MAX_LOAD_TIME:"Max Load Time",
 		END_DATE:"End Date",
      END_KVAH:"End KVAH",
      END_KWH:"End KWH",
      END_RKVAH_LAG:"End Rkvah Lag",
      END_RKVAH_LEAD:"End Rkvah Lead",
	  ELEMENTARY_SECTION_CODE:"Elementary Section Code",
 	  F_NO_OPEN:"F No Open",
	  GRANT_PERIOD:"Grant Period",
	  JOINT_READING_DATE:"Joint Reading Date",
	  OLD_KVAH:"Old KVAH",
	  OLD_RKVAH_LAG:"Old RKVAH Lag",
	  OBSERVATION_ITEM: "Observation Item",
	  OBSERVATION: "Observation",
	  OPEN_DATE:"Open Date",
      OPEN_DONE:"Open Done",
      TPC_NO_OPEN_DONE:"Tpc No Open Done",
      F_NO_OPEN_DONE:"F No Open Done",
      OPEN_BY:"Open By",
      CLOSE:"Close",
      TPC_NO_CLOSE:"Tpc No Close",
      F_NO_CLOSE:"F NO Close",
      CLOSE_DONE:"Close Done",
      TPC_NO_CLOSE_DONE: "Tpc No Close Done",
      F_NO_CLOSE_DONE:"F No Close Done",
      CLOSE_BY:"Close By",
 	  SCHEDULE_FROM_DATE:"Schedule From Date",
      SCHEDULE_TO_DATE:"Schedule To Date",
	  TPC_NO_OPEN:"Tpc No Open",
      APR:"Apr",
      MAY:"May",
      JUN:"Jun",
      JUL:"Jul",
      AUG:"Aug",
      SEP:"Sep",
      OCT:"Oct",
      NOV:"Nov",
      DEC:"Dec",
      JAN:"Jan",
      FEB:"Feb",
      MAR:"Mar",
      TARGETS:"Targets",
      TARGET_TYPE:"Target Type",
      GROUPS_SECTIONS:'Groups Sections',
      USER:"User",
      POINT1_DESCRIPTION:"Point1 Description",
      POINT2_DESCRIPTION:"Point2 Description",
      MEASURE1: "Measure1",
      MEASURE2: "Measure2",
      PREVIOUS1: "Previous1",
      PREVIOUS2: "Previous2",
      PREVIOUS3: "Previous3"
   },
   TITLE:{
     FAILURE_ANALYSIS :"Failure Analysis",
     FAILURE:'Failure',
     MODEL:"Model",
     MAKE:"Make",
     PRODUCT_DATA:'Product Data',
     PRODUCT_CATEGORY_DATA:'Product Category_Data',
     PRODUCT_CATEGORY_MEMBER_DATA:'Product Category Member Data',
     PRODUCT_CATEGORY_FORM:'Product Category Form',
     PRODUCT_CATEGORY_MEMBER_FORM:'Product Category Member Form',
     STANDARD_PHASES_DATA:'Standard Phases Data',
     STANDARD_PHASES_FORM:'Standard Phases Form',
     STANDARD_PHASE_ACTIVITY_DATA:'Standard Phase Activity Data',
     STANDARD_PHASE_ACTIVITY_FORM:'Standard Phase Activity Form',
     GRID_FAILURE:'GRID Failure',
     GROUPS_SECTIONS:'Groups Sections',
     CB_FAILURES:'CB Tripping',
     RC_Failures:'RC Failures',
     RC_FAILURES_FORM:'Rc Failure Form',
     FAILURE_OCCURENCE:'Failure Occurence',
     FAILURE_OCCURRENCE_FORM:'Failure Occurence Form',
     UNUSUAL_OCCURRENCE:'Unusual Occurence ',
     UNUSUAL_OCCURRENCE_FAILURE_FORM:'Unusual Occurrence Failure Form',
     ACTIONS_FORM:'Actions Form',
     CB_FAILURE_FORM:'CB_Tripping_FORM',
     GRID_FAILURE_FORM:'GRID_FAILURE_FORM',
     ASSET_SCHEDULE_ACTIVITY_ASSOC:'Asset Schedule Activity Assoc',
     ASSET_SCHEDULE_ASSOC:'Asset Schedule Assoc',
     FUNCTIONAL_UNIT:'Functional Unit',
     MEASURES_ACTIVITIES:'Measures Activities',
     MEASURE_OR_ACTIVITY:'Measure or Activity',
     STATION_SECTIONS_DATA:'Station Sections  Data',
     STATIONS_SECTIONS:'Stations Sections',
     TPC_BOARD_ASSOC_DATA:'Tpc Board Depot Assoc Data',
     TPC_BOARD_DEPOT_ASSOC:'Tpc Board Depot Assoc',
     TPC_BOARD:'TPC Board',
     TPC_BOARD_DATA:'Tpc Board  Data',
     TSS_FEEDER_MASTER:'TSS FEEDER MASTER',
     FEEDER:'Feeder',
     ASSETS_SCHEDULE_DATA:'Assets Schedule Data',
     ASSETS_SCHEDULE_FORM:'Assets schedule Form',
     DRIVES:'DRIVES',
     DRIVE_FORM:'Drive Form',
     DRIVE_CATEGORY_FORM:'Drive Category Form',
     CHECK_LIST_FORM:'Check List Form',
     DRIVE_DAILY_PROGRESS_FORM:'Drive Daily Progress Form',
     STIPULATION_FORM:'Stipulation Form',
     INSPECTION_FORM:'Inspection Form',
     ASSET_MASTER_DATA:'Asset Master Data',
     ASSET_MASTER_DATA_FORM:'Asset Master Data Form',
     ELECTRIFICATION_TARGETS_FORM:'Electrification Targets Form',
     GUIDANCE:'Guidance',
     SIDINGS_ITEM:'Sidings Item',
     SIDINGS_DATA:'Sidings Data',
     TRACK:'Track',
     OHE_LOCATIONS_DATA:'Ohe Locations Data',
     OHE_LOCATION_FORM:'Ohe Location Form',
     GANTRY_FORM:'Gantry Form',
     GANTRY_DATA: 'Gantry Data',
     SECTOR_FORM:'Sector Form',
     SECTOR_DATA: 'Sector Data',
     SUB_SECTOR_FORM:'Sub Sector Form',
     SUB_SECTOR_DATA: 'Sub Sector Data',
     ELEMENTARY_SECTIONS_FORM:'Elementary Sections Form',
     ELEMENTARY_SECTIONS_DATA: 'Elementary Sections Data',
     FOOT_PATROLLING_SECTIONS_ITEM:'Foot Patrolling Sections Item',
     FOOT_PATROLLING_INSPECTION_ITEM:'Foot Patrolling Inspection Item',
     OBSERVATION_FORM:'Observation Form',
     COMPLIANCE_FORM:'Compliance Form',
     OBSERVATION_CATEGORIES:'Observation Categories',
     OBSERVATION_CHECK_LIST:'Observation Check List',
     ENERGY_BILL_PAYMENT:'EnergyBillPayment',
     ENERGY_CONSUMPTION:'Energy Consumption',
     ENERGY_METER:'Energy Meter',
     TRACTION_ENERGY_TARIFF:'Traction Energy Tariff',
     DAILY_SUMMARY_DATA:'Daily Summary  Data',
     DAILY_SUMMARY_ITEM:'Daily Summary Item',
     SCH_MAINTAINANCE:'SCH Maintainance',
     DRIVE_CATEGORY_ASSOCIATION_FORM:'Drive Category Association Form',
     SIDING_FORM:'Sidings Form',
     WORK:'Work',
     SWITCH_OPERATIONS:'Switch Operations',
     OBSERVATION_CATEGORIES_DATA:'Observation Categories Data',
     OBSERVATIONS_FORM:'OBSERVATIONS_FORM',
    FAILURE_ANALYSIS_FORM:'Failure Analysis Form',
    OBSERVATION_CATEGORY:'Observation Category',
    PROJECT:'Project',
    PROJECT_PHASES:'Project Phases',
    PROJECT_PHASE_ACTIVITY:'Project Phase Activity',
    STANDARD_PHASES:'Standard Phases',
    STANDARD_PHASES_ACTIVITY:'Standard Phases Activity',
    MILESTONE_TARGETS:'Milestone Targets',
    OHE_LOCATIONS_AND_ASSETS_FORM:'OHE Locations And Assets Form',
    OHE_LOCATION_AND_ASSETTYPE_DATA:'OHE Locations And Assets Data' ,
    ASSISTANCE_AND_REMARKS_DATA:'Assistance And Remarks Data',
    ASSISTANCE_AND_REMARKS_FORM:'Assistance And Remarks Form',
    SPECIAL_WORKS_DATA:'Special Works Data',
    SPECIAL_WORKS_MASTER_DATA:'Special Works Master Data',
    SPECIAL_WORKS_FORM:'Special Works Form',
    SPECIAL_WORKS_MATER_FORM:'Special Works Master Form',
    TOWERCAR_STATUS:'TowerCar Status',
    THERMOVISION_MEASURE_INFORMATION: 'Thermovision Measure Information',
    THERMOVISION_CHECK_POINTS:'Thermovision Check Points',
   }
};