export const FieldLabelsConstant = {
   LABELS: {
      ACTION: "Action",
      ACTION_COMPLETED_DATE: "Action Completed Date",
      ACTION_DESCRIPTION: "Action Description",
      ACTION_PLAN: "Action Plan",
      ACTION_REQUIRED: "Action Required",
      ACTION_STATUS: "Action Status",
      ACTION_TARGET_DATE: "Action Target Date",
      ACTIONS: "Actions",
      ACTIVE: "Active",
      ACTIVE_IN_ACTIVE: "Active In-active",
      ACTIVITY: "Activity",
      ACTIVITY_FLAG: "Activity Flag",
      ACTIVITY_ID: "Activity Id",
      ACTIVITY_NAME: "Activity Name",
      ACTIVITY_POSITION: "Activity Position",
      ACTIVITY_POSITION_ID: "Activity Position Id",
      ACTIVITY_POSITION_SEQ: "Activity Position Seq",
      ACTIVITY_TYPE: "Activity Type",
      ACTUAL_FAULT_DISTANCE: "Actual Fault Distance",
      ADEE_SECTION: "Adee Section",
      ALLOCATION: "Allocation",
      ALREADY_DONE: "Already Done",
      ALTITUDE: "Altitude",
      AMOUNT: "Amount",
      APPROVAL_DATE: "Approval Date",
      APPROVED_BY: "Approved By",
      APPROVED_DATE: "Approved Date",
      ASA_SEQ_ID: "Asa Seq Id",
      ASSET_DESCRIPTION: "Asset Description",
      ASSET_ID: "Asset Id",
      ASSET_SCHEDULE: "Asset Schedule",
      ASSET_TYPE: "Asset Type",
      ASSET_TYPE_RLY_ID: "Asset Type Rly Id",
      ASSET_TYPE_SCHEDULE_NAME: "Asset Type Schedule Name",
      AUTHORISATION_DATE: "Authorisation Date",
      AUTHORITY: "Authority",
      BETWEEN_TRAINS: "Between Trains",
      BRAND_NAME: "Brand Name",
      CASCADE_ASSETS: "Cascade Assets",
      CATEGORY_NAME: "Category Name",
      CAUSE_OF_FAILURE: "Cause Of Failure",
      CHAINAGE: "Chainage",
      CHAINAGE_REMARK: "Chainage Remark",
      CHARGING_DATE: "Charging Date",
      CHECK_LIST: "Check List",
      CLOSE_TIME: "Close Time",
      CLOSED_REMARKS: "Closed Remarks",
      CMD: "CMD",
      COMMENTS: "Comments",
      COMPLETION_DATE: "Completion Date",
      COMPLIANCE: "Compliance",
      COMPLIANCE_BY: "Compliance By",
      COMPLIED_BY: "Complied By",
      COMPLIED_DATE: "Complied Date",
      CONDITION: "Condition",
      CREATED_ON: "Created On",
      CRITERIA: "Criteria",
      CROSS_OVER: "Cross Over",
      CRS_AUTHORISATION: "CRS Authorisation",
      CRS_INSPECTION: "CRS Inspection",
      CURRENT: "Current",
      CURVATURE: "Curvature",
      CURVATURE_REMARK: "Curvature Remark",
      DATE: "Date",
      DATE_OF_COMMISSION: "Date Of Commission",
      DATE_OF_COMPLETION: "Date Of Completion",
      DATE_OF_COMPLIED: "Date Of Complied",
      DATE_OF_INSPECTION: "Date Of Inspection",
      DATE_OF_MANUFACTURE: "Date Of Manufacture",
      DATE_OF_RECEIVED: "Date Of Received",
      DATE_OF_STIPULATION: "Date Of Stipulation",
      DAY_PROGRESS: "Day Progress",
      DEPO: "Depo",
      DEPO_TYPE: "Depo Type",
      DEPOT: "Depot",
      DEPOT_NAME: "Depot Name",
      DEPOT_TYPE: "Depot Type",
      DESCRIPTION: "Description",
      DETAILS: "Details",
      DETAILS_OF_ISSUE: "Details Of Issue",
      DETAILS_OF_MAINT: "Details Of Maint",
      DISPLAY_ORDER: "Display Order",
      DIVISION: "Division",
      DIVISION_LOCAL: "Division Local",
      DN_SECTION: "Dn Section",
      DN_SECTION_NAME: "Dn Section Name",
      DOCUMENTS: "Documents",
      DONE_BY: "Done By",
      DOUBLING_TRIPPLING: "Doubling Tripling",
      DOWN_SECTION: "Down Section",
      DOWN_SECTION_NAME: "Down Section Name",
      DRIVE: "Drive",
      DURATION: "Duration",
      ELE_SECTION: "Ele Section",
      ELECTRIFIED_RKM: "Electrified RKM",
      ELECTRIFIED_TKM: "Electrified TKM",
      ELEMENTARY_SECTIONS: "Elementary Sections",
      ENERGISED_DATE: "Energised Date",
      ENG_FEATURE: "Eng Feature",
      EQUIPMENT: "Equipment",
      EQUIPPED_DATE: "Equipped Date",
      ESTIMATED_REVISED_ANTICIPATED_COST: "Estimated Revised Anticipated Cost",
      EXECUTED_BY: "Executed By",
      EXECUTION_AGENCY: "Execution Agency",
      EXPIRY_DATE: "Expiry Date",
      EXTENDED_DURATION: "Extended Duration",
      EXTENDED_FROM: "Extended From",
      EXTENDED_FROM_DATE: "Extended From Date",
      EXTENDED_OFF: "Extended Off",
      EXTENDED_TO_DATE: "Extended To Date",
      FACILITY_NAME: "Facility Name",
      FACILITY_TYPE_ID: "Facility Type Id",
      FAILURE_ACTIONS: "Failure Actions",
      FAILURE_FROM: "Failure From",
      FAILURE_FROM_DATE: "Failure From Date",
      FAILURE_SECTION: "Failure Section",
      FAILURE_THRU: "Failure Thru",
      FAILURE_TO_DATE: "Failure To Date",
      FAULT_DISTANCE: "Fault Distance",
      FEED_EXTENDED_DURATION: "Feed Extended Duration",
      FEED_EXTENDED_FROM: "Feed Extended From",
      FEED_EXTENDED_FROM_DATE_TIME: "Feed Extended From Date Time",
      FEED_EXTENDED_THRU: "Feed Extended Thru",
      FEED_EXTENDED_THRU_DATE_TIME: "Feed Extended Thru Date Time",
      FEED_OF: "Feed Of",
      FEED_OFF: "Feed Off",
      FEEDER: "Feeder",
      FINANCIAL_PROGRESS_PERCENTAGE: "Financial Progress Percentage",
      FOOT_INSPECTION: "Foot Inspection",
      FOOT_PATROLLING: "Foot Patrolling",
      FOOT_PLATE_INSPECTION: "Foot Plate Inspection",
      FP_SECTION: "FP Section",
      FREQUENCY: "Frequency",
      FROM_DATE: "From Date",
      FROM_DATE_TIME: "From Date Time",
      FROM_KILOMETER: "From KM",
      FROM_LOCATION: "From Location",
      FROM_TIME: "From Time",
      FUNCTIONAL_TYPE: "Functional Type",
      FUNCTIONAL_UNIT: "Functional Unit",
      FUNCTIONAL_UNIT_ID: "Functional Unit Id",
      FUNCTIONAL_UNIT_NAME: "Functional Unit Name",
      FUNCTIONAL_UNIT_TYPE: "Functional Unit Type",
      FUNCTIONAL_UNIT_TYPE_ID: "Functional Unit Type Id",
      GANTRY_CODE: "Gantry Code",
      GEN_OPS: "Gen Ops",
      GUAGE: "Guage",
      HEADING: "Heading",
      IDS: "Ids",
      IMPACT: "Impact",
      INCHARGE: "Incharge",
      INDICATION: "Indication",
      INSPECTION: "Inspection",
      INSPECTION_BY: "Inspection By",
      INSPECTION_ID: "Inspection Id",
      INSPECTION_TYPE: "Inspection Type",
      INTERNAL_EXTERNAL: "Internal External",
      IS_DPR: "Is DPR",
      IS_ID_REQUIRED: "Is Id Required",
      IS_NORMALLY_OPENED: "IS Normally Opened",
      JMR: "JMR",
      KILOMETER: "KM",
      KVAH_CONSUMPTION: "KVAH Consumption",
      KVAH_CURRENT: "KVAH Current",
      KVAH_OLD: "KVAH Old",
      KWH_CONSUMPTION: "KWH Consumption",
      KWH_CURRENT: "KWH Current",
      KWH_OLD: "KWH Old",
      LATEST_REVISED_COST: "Latest Revised Cost",
      LATITUDE: "Latitude",
      LETTER_NO: "Letter No",
      LOCATION: "Location",
      LOCATION_POSITION: "Location Position",
      LOCATION_TYPE: "Location Type",
      LONGITUDE: "Longitude",
      LONGITUDINAL_DN: "Longitudinal Dn",
      LONGITUDINAL_UP: "Longitudinal Up",
      LOWER_LIMIT: "Lower Limit",
      LUG_DATE: "Lug Date",
      MAJOR_SECTION: "Major Section",
      MAJOR_SECTION_ROUTE: "Major Section Route",
      MAKE: "Make",
      MAKE_CODE: "Make Code",
      MAKE_TYPE: "Make Type",
      MATERIAL_CLASSIFICATION: "Material Classification",
      MAX_DEMAND: "Max Demand",
      MEASURE_ACTIVITY_LIST: "Measure Activity List",
      MEASURE_ENTRY: "Measure Entry",
      MEASURE_LOWER_LIMIT: "Measure Lower Limit",
      MEASURE_UPPER_LIMIT: "Measure Upper Limit",
      METER_MAKE: "Meter Make",
      METER_MODEL: "Meter Model",
      METER_NUMBER: "Meter Number",
      MF: "MF",
      MODEL: "Model",
      MODEL_CODE: "Model Code",
      MODEL_TYPE: "Model Type",
      MONTH: "Month",
      MULTIPLICATION_FACTOR: "Multiplication Factor",
      NAME: "Name",
      NAME_OF_STAFF: "Name Of Staff",
      NATURE_OF_CLOSURE: "Nature Of Closure",
      NON_POWER_BLOCK: "Non Power Block",
      NORMALLY_OPEN: "Normally Open",
      NPB_PROGRESS: "NPB Progress",
      OBSERVATION_CATEGORY: "Observation Category",
      OBSERVATION_ITEM: "Observation Item",
      OCCURENCE: "Occurrence",
      OCCURRED_DATE: "Occurred Date",
      OHE_FEATURE: "OHE Feature",
      OHE_MAST: "OHE Mast",
      OHE_MAST_TYPE: "OHE Mast Type",
      OHE_SEQUENCE: "OHE Sequence",
      PARENT_FUN: "Parent Fun",
      PARENT_FUN_UNIT: "Parent Fun Unit",
      PB_SECTION: "PB Section",
      PERFORMED_COUNT: "Performed Count",
      PERFORMED_DATE: "Performed Date",
      PHASE: "Phase",
      PHASE_ANGLE: "Phase Angle",
      PHYSICAL_PROGRESS_PERCENTAGE: "Physical Progress Percentage",
      PL_NO: "Pl No",
      PLACE: "Place",
      POPULATION: "Population",
      POWER_BLOCK: "Power Block",
      PRIMARY_PARENT_CATEGORY_ID: "Primary Parent Category Id",
      PRIMARY_PRODUCT: "Primary Product",
      PRIMARY_PRODUCT_CATEGORY_ID: "Primary Product Category Id",
      PRIMARY_PRODUCT_CATEGORYID: "Primary Product Category Id",
      PRIORITY: "Priority",
      PRIVATE_RAILWAY: "Private Railway",
      PRODUCT_CATEGORY_ID: "Product Category Id",
      PRODUCT_CATEGORY_TYPE_ID: "Product Category Type Id",
      PRODUCT_ID: "Product Id",
      PRODUCT_TYPE_ID: "Product Type Id",
      PROPOSAL_SCHEME: "Proposal Scheme",
      PROPOSED_DATE: "Proposed Date",
      PROTECTION_LONGITUDINAL_DN: "Protection Longitudinal Dn",
      PROTECTION_LONGITUDINAL_UP: "Protection Longitudinal Up",
      PROTECTION_TRAVERSE_CROSSOVER: "Protection Traverse Crossover",
      PROTECTION_TRAVERSE_TURNOUT: "Protection Traverse Turnout",
      PSI_PROGRESS: "PSI Progress",
      PURPOSE: "Purpose",
      PWI: "PWI",
      QUANTITY: "Quantity",
      QUANTITY_UOM_ID: "Quantity Uom Id",
      R_VALUE: "R Value",
      RATE: "Rate",
      RECTIFIED_DATE: "Rectified Date",
      REFERENCE: "Reference",
      RELAY_IND: "Relay Ind",
      RELAY_INDICATION: "Relay Indication",
      REMARK: "Remark",
      REMARK_ONE: "Remark One",
      REMARK_TWO: "Remark Two",
      REMARKS: "Remarks",
      REPERCUSSION: "Repercussion",
      REPORT_CONTINUE: "Report Continue",
      REPORT_DESCRIPTION: "Report Description",
      REPORTED: "Reported",
      REQUEST_BY: "Request By",
      REQUEST_DEPARTMENT: "Request Department",
      REQUEST_PERIOD_IN_MIN: "Request Period In MIN",
      RESOLVE_TIME: "Resolve Time",
      RESPONSE: "Response",
      RKM: "RKM",
      RKVAH_LAG_CONSUMPTION: "RKVAH Lag Consumption",
      RKVAH_LAG_CURRENT: "RKVAH Lag Current",
      RKVAH_LAG_OLD: "RKVAH Lag Old",
      RKVAH_LEAD_CONSUMPTION: "RKVAH Lead Consumption",
      RKVAH_LEAD_CURRENT: "RKVAH Lead Current",
      RKVAH_LEAD_OLD: "RKVAH Lead Old",
      RLY_ID: "Rly Id",
      ROOT_CAUSE: "Root Cause",
      S_NO: "S No",
      SANCTION_BY_BOARD: "Sanction By Board",
      SANCTION_COST: "Sanction Cost",
      SATELLITES: "Satellites",
      SCHEDULE: "Schedule",
      SCHEDULE_CODE: "Schedule Code",
      SCHEDULE_DATE: "Schedule date",
      SCHEDULE_DURATION: "Schedule Duration",
      SCHEDULE_NAME: "Schedule Name",
      SECTION: "Section",
      SECTION_ELECTRIFIED_STATUS: "Section Electrified Status",
      SECTION_END_LOCATION: "Section End Location",
      SECTION_START_LOCATION: "Section Start Location",
      SECTION_STATUS: "Section Status",
      SELECT_EXECUTION_AGENCY: "Select Execution Agency",
      SEQUENCE_CODE: "Sequence Code",
      SEVERITY: "Severity",
      SHORT_DESCRIPTION: "Short Description",
      SIDING_CODE: "Siding Code",
      SIDING_ELECTRIFIED_STATUS: "Siding Electrified Status",
      SIDING_PROPOSED: "Siding Proposed",
      SIDING_STATUS: "Siding Status",
      SIZE: "Size",
      SPECIFICATION: "Specification",
      SPEED: "Speed",
      STAFF_STRENGTH: "Staff Strength",
      START_DATE: "Start Date",
      START_KVAH: "Start KVAH",
      START_KWH: "Start KWH",
      START_RKVAH_LAG: "Start RKVAH Lag",
      START_RKVAH_LEAD: "Start RKVAH Lead",
      START_TIME: "Start Time",
      STATE: "State",
      STATE_ELECTRICITY_BOARD: "state Electricity Board",
      STATION: "Station",
      STATION_CODE: "Station Code",
      STATUS: "Status",
      STATUS_REMARKS: "Status Remarks",
      STIPULATION: "Stipulation",
      STOP_TIME: "Stop Time",
      STRIP_DATE: "Strip Date",
      STRUCTURE_TYPE: "Structure Type",
      SUB_ASSET_ID: "Sub Asset Id",
      SUB_ASSET_TYPE: "Sub Asset Type",
      SUB_DIV: "Sub Div",
      SUB_STATION: "Sub Station",
      SUPERVISOR: "Supervisor",
      SUPPLIER: "Supplier",
      SWITCH: "Switch",
      SWITCH_ID: "Switch Id",
      SWITCH_TYPE: "Switch Type",
      SWITCHING_STATION: "Switching Station",
      TARGET: "Target",
      TARGET_DATE: "Target Date",
      TARGET_PLAN: "Target Plan",
      TARGET_PLAN_MONTHS: "Target Plan Months",
      TARGET_QUANTITY: "Target Quantity",
      TARGET_SET_BY: "Target Set By",
      THRU_DATE: "Thru Date",
      THRU_DATE_TIME: "Thru Date Time",
      THRU_TIME: "Thru Time",
      TKM: "TKM",
      TO_DATE: "To Date",
      TO_KILOMETER: "To KM",
      TO_LOCATION: "To Location",
      TO_PAYMENT: "To Payment",
      TOMORROW_FORECAST: "Tomorrow Forecast",
      TPC_BOARD: "TPC Board",
      TRACK_LINE: "Track Line",
      TRAIN_NO: "Train No",
      TRAVERSE_TURNOUT: "Traverse Turnout",
      TRIP_IDENTIFIED_FAULT: "Trip Identified Fault",
      TRIP_TIME: "Trip Time",
      TRIPPED_IDENTIFIED_FAULT: "Tripped Identified Fault",
      TYPE: "Type",
      TYPE_OF_FAILURE: "Type Of Failure",
      UNIT_NAME: "Unit Name",
      UNIT_OF_MEASURE: "Unit Of Measure",
      UNIT_TYPE: "Unit Type",
      UNITS: "Units",
      UOM_OF_DURATION: "Uom Of Duration",
      UP_SECTION: "UP Section",
      UP_SECTION_NAME: "UP Section Name",
      UPPER_LIMIT: "Upper Limit",
      VALID_TILL_DATE: "Valid Till Date",
      VALIDITY: "Validity",
      VOLTAGE: "Voltage",
      WARRANTY_AMC_ENDDATE: "Warranty AMC End Date",
      WORK_NAME: "Work Name",
      WORK_ORDER_DATE: "Work Order Date",
      WORK_PROGRESS_PERCENTAGE: "work progress percentage",
      WORK_PROGRESS_REMARK: "Work Progress Remark",
      X_VALUE: "X Value",
      YEAR: "Year",
      YEAR_OF_SANCTION: "Year Of Sanction",
      Z_CONSTANT: "Z Constant",
      ZONE: "Zone",
   },
   TITLE:{
     FAILURE_ANALYSIS :"Failure Analysis",
     FAILURE:'Failure',
     MODEL:"Model",
     MAKE:"Make",
     PRODUCT_DATA:'Product_Data',
     PRODUCT_CATEGORY_DATA:'Product Category_Data',
     PRODUCT_CATEGORY_FORM:'Product Category Form',
     PRODUCT_CATEGORY_MEMBER_FORM:'Product Category Member Form',
     GRID_FAILURE:'GRID Failure',
     CB_FAILURES:'CB Failures',
     RC_Failures:'RC Failures',
     RC_FAILURES_FORM:'Rc Failure Form',
     FAILURE_OCCURENCE:'Failure Occurence',
     FAILURE_OCCURRENCE_FORM:'Failure Occurrence Form',
     UNUSUAL_OCCURRENCE:'Unusual Occurence ',
    UNUSUAL_OCCURRENCE_FAILURE_FORM:'Unusual Occurrence Failure Form',
    ACTIONS_FORM:'Actions Form',
    CB_FAILURE_FORM:'CB_FAILURE_FORM',
    GRID_FAILURE_FORM:'GRID_FAILURE_FORM'

   }
};