export interface AssetMasterDataModel {   
    id: number;
    adeeSection:string,
    assetId :string,
    assetType:string,
    batch:string,
    bracket1InsulatorBatch :string,  
    bracket1InsulatorMake :string,
    bracket2InsulatorBatch :string,
    bracket2InsulatorMake :string,
    bracket3InsulatorBatch :string,
    bracket3InsulatorMake :string,
    capacityRating :string,
    codalLife :string,
    core1InsulatorBatch:string,
    core1InsulatorMake:string,
    core2InsulatorMake:string,
    core2InsulatorBatch:string,
    core3InsulatorBatch:string,
    core3InsulatorMake:string,
    createdBy:string,
    createdOn:string;
    createdStamp:any;
    createdTxStamp: any;
    lastUpdatedStamp:any;
    lastUpdatedTxStamp:any;
    dateOfCommision:string,
    dateOfManufacture:string,
    dateOfReceived:string,
    elementarySection:string,
    end1Side1:string,
    end2Side2:string,
    equippedDate:string,
    expiryDate:string,
    facilityId:string,
    implantation:string,
    kilometer:string,
    line:string,
    locationPosition:string,
    lugDate:string,
    majorSection:string,
    make:string,
    model:string,
    namePlateDetails:string,
    oemSerial:string,
    parentAssetType:string,
    parentAssetTypeId:string,
    part1:string,
    part2:string,
    part3:string,
    pedestal1InsulatorBatch:string,
    pedestal1InsulatorMake:string,
    pedestal2InsulatorBatch:string,
    pedestal2InsulatorMake:string,
    pedestal3InsulatorBatch:string,
    pedestal3InsulatorMake:string,
    positionId:string,
    remark1:string,
    remark2:string,
    rlyAssignedSerial:string,
    rod1InsulatorBatch:string,
    rod1InsulatorMake:string,
    rod2InsulatorBatch:string,
    rod2InsulatorMake:string,
    rod3InsulatorBatch:string,
    rod3InsulatorMake:string,
    section:string,
    source:string,
    stag1Ton9InsulatorBatch:string,
    stag1Ton9InsulatorMake:string,
    stag2Ton9InsulatorBatch:string,
    stag2Ton9InsulatorMake:string,
    stag3Ton9InsulatorBatch:string,
    stag3Ton9InsulatorMake:string,
    stagger:string,
    stagger1:string,
    stagger2:string,
    stagger3:string,
    station:string,
    stay1InsulatorBatch:string,
    stay1InsulatorMake:string,
    stay2InsulatorBatch:string,
    stay2InsulatorMake:string,
    stay3InsulatorBatch:string,
    stay3InsulatorMake:string,
    stripDate:string,
    structure:string,
    type:string,
    vendor:string,
    voltage:string,
    warrantyAmc:string,
    warrantyAmcEndDate:string


  }
  