export class ReportModel{
    outputData: any;
    reportName: string;
    reportHeader: string;
    zone:any;
    division: any;
    subDivision:any;
    permission:String;
    depot:string;
    tpcBoard:string;
    facility:any;
    facilityId:any;
    reportId:any;
    id:any;
    productId : any;
    fromDate:any;
    toDate:any;
    failureFromDate:any;
    failureToDate:any;
    department:any;
    observationCategory:any;
    reportCategory:any;
    scheduleCode:any;
    assetType:any;
    assetId:any;
    scheduleDate:any;
    activityType:any;
    year:any;
    switchType:any;
    pbSwitchType:any;
    pbExtentCode:any;
    elementarySectionCode:any;
    fromkm:any;
    tokm:any;
    formatType: string;
    locationTypes:any;
    depotType:any;
    materialItem:any; 
    workName:any;
    group:any;
    workSection:any;
    agency:any;
    WpaName:any;
    driveName:any;
    feederName:any;
}